SET( CMAKE_SYSTEM_NAME QNX )
SET( CMAKE_SYSTEM_VERSION 7.0.0 )
SET( TOOLCHAIN QNX )
SET( LIBRARY_PREFIX lib)
SET( LIBRARY_SUFFIX .so)
message(STATUS "Toolchain QNX700")
SET( QNX_HOST $ENV{QNX_HOST})
SET( QNX_TARGET  $ENV{QNX_TARGET})

IF(CMAKE_HOST_WIN32)
	set(EXTENSION ".exe")
ENDIF()

# set cmake toolchains 
SET( CMAKE_MAKE_PROGRAM "${QNX_HOST}/usr/bin/make${EXTENSION}"    CACHE PATH "QNX Make Program" )
SET( CMAKE_SH           "${QNX_HOST}/usr/bin/sh${EXTENSION}"      CACHE PATH "QNX shell Program" )
SET( CMAKE_AR           "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-ar${EXTENSION}"      CACHE PATH "QNX ar Program" )
SET( CMAKE_RANLIB       "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-ranlib${EXTENSION}"      CACHE PATH "QNX ranlib Program" )
SET( CMAKE_NM           "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-nm${EXTENSION}"      CACHE PATH "QNX nm Program" )
SET( CMAKE_OBJCOPY      "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-objcopy${EXTENSION}" CACHE PATH "QNX objcopy Program" )
SET( CMAKE_OBJDUMP      "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-objdump${EXTENSION}" CACHE PATH "QNX objdump Program" )
SET( CMAKE_LINKER       "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-ld${EXTENSION}"     CACHE PATH "QNX Linker Program" )
SET( CMAKE_STRIP        "${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-strip${EXTENSION}"   CACHE PATH "QNX Strip Program" )
SET( CMAKE_C_COMPILER ${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-gcc${EXTENSION} )
SET( CMAKE_CXX_COMPILER ${QNX_HOST}/usr/bin/aarch64-unknown-nto-qnx7.0.0-g++${EXTENSION} )

SET( CMAKE_FIND_ROOT_PATH ${QNX_TARGET} )
SET( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
SET( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
SET( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )

add_definitions("-DKZ_SUPPORT_GRAPHICS_CONTEXT_API_EGL=1")
add_definitions("-DKZ_SUPPORT_GRAPHICS_API_GLES=1")
add_definitions("-DKZ_LINKED_GLES_SYMBOLS=31")
add_definitions("-DKZ_DLOAD_GLES_SYMBOLS=31")
add_definitions("-DKANZI_FEATURE_3D")
add_definitions("-DQNX")
add_definitions("-DQNX_SCREEN")
add_definitions("-D_QNX_SOURCE")
set(CMAKE_CXX_FLAGS "-fexceptions -frtti -O2 -fPIC -Wall -Wextra -Wno-overlength-strings -fno-strict-aliasing -Wno-maybe-uninitialized")
